apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-operator
  namespace: platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: git-operator
  namespace: platform-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-operator-leader-election
  namespace: platform-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: git-operator
rules:
- apiGroups:
  - git.flanksource.com
  resources:
  - gitopsapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.flanksource.com
  resources:
  - gitopsapis/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-operator
  namespace: platform-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-operator
subjects:
- kind: ServiceAccount
  name: git-operator
  namespace: platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-operator-leader-election
  namespace: platform-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-operator-leader-election
subjects:
- kind: ServiceAccount
  name: git-operator
  namespace: platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: git-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: git-operator
subjects:
- kind: ServiceAccount
  name: git-operator
  namespace: platform-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: git-operator
  name: git-operator
  namespace: platform-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: git-operator
  template:
    metadata:
      labels:
        control-plane: git-operator
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --log-level=debug
        command:
        - /git-operator
        image: flanksource/git-operator:v1
        imagePullPolicy: IfNotPresent
        name: git-operator
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      serviceAccountName: git-operator
      terminationGracePeriodSeconds: 10
